# plotter_config.yaml
# 2026-May-5

genome_reference: mm10                 # Versión del genoma

hic:
  directory: /Users/amaury/lines/mouse/endothelial_Cells/juicer/
  ctrl_file: Ctcf_WT.allReps.896MvP.hic
  file: Ctcf_KO.allReps.896MvP.hic

  names:
    - Ctcf_WT
    - Ctcf_KO
    - Ctcf-KO - Ctcf-WT

  resolution: 10000

  matrix_choices:
    - log2_ctrl
    - log2
    - subtraction

  min_plot:
    - 3
    - 3
    - -40

  max_plot:
    - 12
    - 12
    - 30

heatmap_legends:

  show:
    - true
    - true
    - true

  position_x:
    - -0.08
    - -0.08
    - -0.08

  position_y:
    - 0.5
    - 0.5
    - 0.5

  direction:
    - vertical
    - vertical
    - vertical

  title_size:
    - 5
    - 5
    - 5

  text_size:
    - 5
    - 5
    - 5

  key_height:
    - 7
    - 7
    - 7

  key_width:
    - 5
    - 5
    - 5

marks:

  names:
    - ATAC_WT
    - ATAC_KO
    - RNAseq_WT
    - RNAseq_KO
    - H3K4me3
    - H3K4me1
    - H3K27ac
    - H3K27me3
    - CTCF

  files:
    - /Users/amaury/toronto_CUTNTag/bigwigs_ATAC_hisat2/ys211.ATACseq.WT.trim_Ad_3pb.h2.0_120pb.scaleFact.bw

    - /Users/amaury/toronto_CUTNTag/bigwigs_ATAC_hisat2/ys300.ATACseq.Ctcf_KO.trim_Ad_3pb.h2.0_120pb.scaleFact.bw

    - /Users/amaury/toronto_CUTNTag/bigwigs_normalized_by_SF/rnaseq.Ctcf_WT.trim.paired.star.scaleFact.bw
    - /Users/amaury/toronto_CUTNTag/bigwigs_normalized_by_SF/rnaseq.Ctcf_KO.trim.single.star.scaleFact.bw
    - /Users/amaury/toronto_CUTNTag/bigwigs_normalized_by_SF/H3K4me3.Ctcf_WT.trim_Ad_3pb.h2.scaleFact.bw
    - /Users/amaury/toronto_CUTNTag/bigwigs_normalized_by_SF/H3K4me1.Ctcf_WT.trim_Ad_3pb.h2.scaleFact.bw
    - /Users/amaury/toronto_CUTNTag/bigwigs_normalized_by_SF/H3K27ac.Ctcf_WT.ys204_ys240.trim_Ad_3pb.h2.scaleFact.bw
    - /Users/amaury/toronto_CUTNTag/bigwigs_normalized_by_SF/H3K27me3.Ctcf_WT.trim_Ad_3pb.h2.scaleFact.bw
    - /Users/amaury/toronto_CUTNTag/bigwigs_normalized_by_SF/Ctcf.Ctcf_WT.ys115_ys200.trim_Ad_3pb.h2.scaleFact.bw

  colors:
    - black
    - black
    - pink4
    - pink4
    - orange1
    - yellow4
    - green4
    - red3
    - blue3

  track_offset:
    - 10
    - 9
    - 8
    - 7
    - 6
    - 5
    - 4
    - 3
    - 2

  labels_offset:
    - 10.5
    - 9.5
    - 8.5
    - 7.5
    - 6.5
    - 5.5
    - 4.5
    - 3.5
    - 2.5

  track_height:
    - 1 # ATACseq tracks are taller to be more visible
    - 1 # ATACseq tracks are taller to be more visible
    - 4 # RNAseq tracks are shorter to avoid dominating the plot
    - 4 # RNAseq tracks are shorter to avoid dominating the plot
    - 8 # H3K4me3
    - 30 # H3K4me1
    - 100 # H3K27ac
    - 20 # H3K27me3
    - 70 # CTCF

  label_size: 6

  bin_size:
    - 400
    - 400
    - 300
    - 300
    - 300
    - 300
    - 300
    - 300
    - 400

  crop:
    - true

  max_height:
    - 0.95

genes:
  
  genes_files:
    - /Users/amaury/toronto_CUTNTag/only_CTCF_motifs/CTCF_MA0139_MA1929_MA1930.meme/Ctcf.ATACseq/Ctcf.ATACseq.Ctcf_WT_KO.Ctcf_motifs.plus_minus.1kb_extended.bed
    - /Users/amaury/genes/Ctcf_WT_KO.DEGs.filtered_by_Tie2_ATAC.Accesible_Inaccesible.genebody.bed
    - /Users/amaury/genes/mm10.gene.track.sym.sorted.bed

  offset:
    - 1.5 
    - 11.7
    - 12.7

  labels: 
    - "CTCF Sense"
    - DEGs
    - Genes

  labels_offset: 
    - 1.5
    - 11.7
    - 12.7

  height: 
    - 0.1
    - 0.15
    - 0.03

  label_size: 
    - 2
    - 2
    - 0.5

  show_label: 
    - false
    - true
    - false

  jitter:
    - 0.4
    - 0.4
    - 0.25  

plot:

  proportions:
    - 1
    - 1
    - 1
    - 2.5

  directory: /Users/amaury/lastHiC_analysis/plots_rplotter

  format: png

  height: 15
  
  width: 10

  tracks_limits:
    - 1
    - 13.1

shared_yaxis_groups:

  ATACseq:
    - ATAC_WT
    - ATAC_KO

  RNAseq:
    - RNAseq_WT
    - RNAseq_KO
