# metatracks_config.yaml

global:

  output_dir: "/Users/amaury/lastHiC_analysis/metatracks_output_test"
  density_plot_width: 12
  ncores: 1

  aggreagation_stat:
    label: "Mean_Score"
    method: "mean"
    
  alpha_level: 1
  chromosome_prefix_in_bw: "chr"

  dimensions:
    resol: 5000
    TAD_extend: 0.5
    distance_To_Nearest_TAD: 400000
    nbins: 50
    in_boundaries_pb_up: 5000
    in_boundaries_pb_down: 5000
    near_boundaries_pb_up: 5000
    near_boundaries_pb_down: 5000
    out_boundaries_pb_up: 5000
    out_boundaries_pb_down: 5000
    anchor_bin_size: 1000

  output:
    formato: "pdf"
    row_height: 0.005
    base_height: 2.5

regions:
  TADs: 
    - /Users/amaury/hicToronto/TADs_vs_Loops/bedpes/Ctcf_WT.allReps.896MvP.arrowHead.300sample.bedpe
    - chr1,start1,end1,chr2,start2,end2,id
  DEGs: 
    - /Users/amaury/genes/Ctcf_WT_KO.DEGs.filtered_by_Tie2_ATAC.Accesible_Inaccesible.promoters.bed
    - chr,start,end,id,score,strand,exonstart,exonend,color,accessibility,cluster
    - cluster #grouping variable, should be the same as the ones in samples 
  Ctrl: 
    - /Users/amaury/genes/active_genes.Tie2_YS.TPMs.2_clusters.promoters.2kb_1kb.bed
    - chr,start,end,id,score,strand,exonstart,exonend,color,exonN,thickStart,thickEnd,cluster

marks:
  files:
    H3K4me1: /Users/amaury/toronto_CUTNTag/bigwigs_normalized_by_SF/H3K4me1.Ctcf_WT.trim_Ad_3pb.h2.scaleFact.bw
    H3K27me3: /Users/amaury/toronto_CUTNTag/bigwigs_normalized_by_SF/H3K27me3.Ctcf_WT.trim_Ad_3pb.h2.scaleFact.bw
  colors:
    H3K4me1: yellow4
    H3K27me3: red3

samples:

  Monocytes:
    peaks_density_limits:
      H3K4me1: [null, null, null, null]
      H3K27me3: [null, null, null, null]

  Reticulocytes_Low:
    peaks_density_limits:
      H3K4me1: [null, null, null, null]
      H3K27me3: [null, null, null, null]

  Reticulocytes_High:
    peaks_density_limits:
      H3K4me1: [null, null, null, null]
      H3K27me3: [null, null, null, null]

  Endothelial_High:
    peaks_density_limits:
      H3K4me1: [null, null, null, null]
      H3K27me3: [null, null, null, null]

  Endothelial_Low:
    peaks_density_limits:
      H3K4me1: [null, null, null, null]
      H3K27me3: [null, null, null, null]

  Cardiomyocytes:
    peaks_density_limits:
      H3K4me1: [null, null, null, null]
      H3K27me3: [null, null, null, null]